import type { AgendaEntry } from "./agenda"

export const agendaData: AgendaEntry[] = [
  {
    id: "break-1",
    type: "break",
    time: "14:00",
    label: "ACREDITACIÓN",
  },
  {
    id: "1",
    type: "talk",
    time: "14:30",
    title: "Liderazgo Femenino Cuando Eres Minoría en el mundo de la Tecnología",
    titleSize: "xs",
    name: "Maria Belen Camargo Aramayo",
    img: "/events/iwd-26/speakers/speaker-3.webp",
    skill: "Productividad",
  },
  {
    id: "2",
    type: "talk",
    time: "15:10",
    title: "Inteligencia Artificial con propósito: de usuaria a creadora del futuro",
    titleSize: "xs",
    name: "Sara Oneydi Salazar Paredes",
    img: "/events/iwd-26/speakers/speaker-1.webp",
    skill: "IA",
  },
  {
    id: "3",
    type: "talk",
    time: "15:50",
    title: 'Del "No vas a poder" al "¡Mira cómo lo hago!"',
    titleSize: "sm",
    name: "Melvy Rocío Ancieta Alvarado",
    img: "/events/iwd-26/speakers/speaker-2.webp",
    skill: "Productividad",
  },
  {
    id: "break-2",
    type: "break",
    time: "16:25",
    label: "REFRIGERIO",
  },
  {
    id: "4",
    type: "talk",
    time: "16:35",
    title: "Liderazgo No-Lineal",
    titleSize: "base",
    name: "Nataly Alejandra Gemio Morales",
    img: "/events/iwd-26/speakers/speaker-4.webp",
    skill: "Productividad",
  },
  {
    id: "5",
    type: "talk",
    time: "17:10",
    title: "De la idea a la acción: productividad estratégica para mujeres en entornos digitales",
    titleSize: "xs",
    name: "Sharon Lourdes Alvarado C.",
    img: "/events/iwd-26/speakers/speaker-5.webp",
    skill: "Internet de las cosas IOT",
  },
]
