CREATE TABLE IF NOT EXISTS "public"."teams" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "event_id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "code" "text" NOT NULL
);

ALTER TABLE "public"."teams" OWNER TO "postgres";

ALTER TABLE "public"."teams" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."teams_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."team_registrations" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "team_id" bigint NOT NULL,
    "registration_id" bigint NOT NULL,
    "leader" boolean DEFAULT false NOT NULL
);

ALTER TABLE "public"."team_registrations" OWNER TO "postgres";

ALTER TABLE "public"."team_registrations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."team_registrations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Primary keys
ALTER TABLE ONLY "public"."teams"
    ADD CONSTRAINT "teams_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."team_registrations"
    ADD CONSTRAINT "team_registrations_pkey" PRIMARY KEY ("id");

-- Foreign keys
ALTER TABLE ONLY "public"."teams"
    ADD CONSTRAINT "teams_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."team_registrations"
    ADD CONSTRAINT "team_registrations_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."team_registrations"
    ADD CONSTRAINT "team_registrations_registration_id_fkey" FOREIGN KEY ("registration_id") REFERENCES "public"."registrations"("id") ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS "teams_event_id_idx"
    ON "public"."teams" ("event_id");

CREATE INDEX IF NOT EXISTS "team_registrations_team_id_idx"
    ON "public"."team_registrations" ("team_id");

-- Constraints
ALTER TABLE ONLY "public"."teams"
    ADD CONSTRAINT "teams_event_id_code_key" UNIQUE ("event_id", "code");

ALTER TABLE ONLY "public"."team_registrations"
    ADD CONSTRAINT "team_registrations_unique_key"
    UNIQUE ("team_id", "registration_id");

ALTER TABLE ONLY "public"."team_registrations"
    ADD CONSTRAINT "team_registrations_registration_id_key" UNIQUE ("registration_id");

CREATE UNIQUE INDEX IF NOT EXISTS "team_registrations_one_leader_per_team_idx"
    ON "public"."team_registrations" ("team_id")
    WHERE "leader";

-- Triggers para updated_at automático
CREATE OR REPLACE TRIGGER "update_updated_at_teams"
    BEFORE UPDATE ON "public"."teams"
    FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

CREATE OR REPLACE TRIGGER "update_updated_at_team_registrations"
    BEFORE UPDATE ON "public"."team_registrations"
    FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

-- RLS
ALTER TABLE "public"."teams" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."team_registrations" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all to authenticated users" ON "public"."teams" TO "authenticated" USING (true);
CREATE POLICY "Allow all to authenticated users" ON "public"."team_registrations" TO "authenticated" USING (true);
